### PR TITLE
Iverilog testing

### PR DESCRIPTION
**Pull request by peteasa**
Here are a few changes that might help.
emailbox read is failing because mailbox_fifo_data must be sampled by rd_clk and this then results in the rxrr_fifo getting the data late so the first read is garbage and the second read gets the previous data!  Working out how to delay the cycle.

### CODE REVIEW

**Comment by aolofsson** [comment]
Sorry for the crazyness...finally getting back to this. I have updated the dv environment and the run instructions.(so we will need to rebase) Concerned that you had to add the rest to get it to work. I am not seeing that problem? Now working on testing the mailbox.

**Comment by aolofsson** [comment]
Never mind....test passing, but bursting bug(s) were masked.

**Comment by peteasa** [comment]
I may have a reason why my simulations are different.  I just discovered that if I run the simulation after running the configure / make elink steps then I get different results.  Seems like you need to build the solution first.  

So I think that the readme file should say..
source ~/local/xilinx/Vivado/2015.2/settings64.sh 
mkdir build
cd build
../configure
make package_axi_elink
make elink
cd ../oh/elink/dv
./build.sh
./run.sh test/test_basic.memh

**Comment by peteasa** [comment]
quite a lot has changes so I will close this

**Pull request closed without merging**
